server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=item-service
spring.cloud.gateway.routes[0].uri=${ITEM_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/items/**

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=${ORDER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=${PAYMENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/payments/**